const Map<String, dynamic> phonemeRehabData = {
  'level_2': [
    // --- ZONA ALTA (6kHz - 8kHz): Sibilantes e Fricativas Agudas ---
    {'target': 'Selo', 'distractor': 'Felo', 'freq_band': 6500, 'type': 'fricative'},
    {'target': 'Saca', 'distractor': 'Faca', 'freq_band': 7000, 'type': 'high_f'},
    {'target': 'Sino', 'distractor': 'Fino', 'freq_band': 7500, 'type': 'fricative'},
    {'target': 'Sete', 'distractor': 'Fete', 'freq_band': 6200, 'type': 'high_f'},
    {'target': 'Sina', 'distractor': 'Fina', 'freq_band': 7800, 'type': 'fricative'},
    {'target': 'Sala', 'distractor': 'Fala', 'freq_band': 6800, 'type': 'fricative'},
    {'target': 'Sopa', 'distractor': 'Fopa', 'freq_band': 6400, 'type': 'high_f'},
    {'target': 'Seda', 'distractor': 'Feda', 'freq_band': 6600, 'type': 'fricative'},
    {'target': 'Soma', 'distractor': 'Foma', 'freq_band': 7200, 'type': 'high_f'},
    {'target': 'Sela', 'distractor': 'Zela', 'freq_band': 6000, 'type': 'voiced_fricative'},
    {'target': 'Sosso', 'distractor': 'Fosso', 'freq_band': 8000, 'type': 'ultra_high'},
    {'target': 'Assa', 'distractor': 'Acha', 'freq_band': 6500, 'type': 'sibilant'},
    {'target': 'Passo', 'distractor': 'Pacho', 'freq_band': 6700, 'type': 'sibilant'},
    {'target': 'Cesta', 'distractor': 'Festa', 'freq_band': 6900, 'type': 'high_f'},
    {'target': 'Soco', 'distractor': 'Foco', 'freq_band': 7100, 'type': 'fricative'},

    // --- ZONA MÉDIA (3kHz - 5kHz): Plosivas e Transições ---
    {'target': 'Tia', 'distractor': 'Pia', 'freq_band': 4200, 'type': 'plosive'},
    {'target': 'Chave', 'distractor': 'Sabe', 'freq_band': 4800, 'type': 'sibilant'},
    {'target': 'Massa', 'distractor': 'Mata', 'freq_band': 5200, 'type': 'sibilant'},
    {'target': 'Vila', 'distractor': 'Fila', 'freq_band': 3800, 'type': 'labiodental'},
    {'target': 'Zelo', 'distractor': 'Selo', 'freq_band': 4500, 'type': 'voiced_fricative'},
    {'target': 'Gato', 'distractor': 'Cato', 'freq_band': 3200, 'type': 'velar'},
    {'target': 'Data', 'distractor': 'Tata', 'freq_band': 3500, 'type': 'plosive'},
    {'target': 'Bala', 'distractor': 'Pala', 'freq_band': 3000, 'type': 'bilabial'},
    {'target': 'Dedo', 'distractor': 'Tedo', 'freq_band': 3400, 'type': 'plosive'},
    {'target': 'Vento', 'distractor': 'Bento', 'freq_band': 4100, 'type': 'fricative_plosive'},
    {'target': 'Jato', 'distractor': 'Xato', 'freq_band': 4600, 'type': 'postalveolar'},
    {'target': 'Gelo', 'distractor': 'Chelo', 'freq_band': 4400, 'type': 'postalveolar'},
    {'target': 'Vaca', 'distractor': 'Faca', 'freq_band': 3900, 'type': 'fricative'},
    {'target': 'Zero', 'distractor': 'Sero', 'freq_band': 4300, 'type': 'voiced_sibilant'},
    {'target': 'Pote', 'distractor': 'Bote', 'freq_band': 3100, 'type': 'plosive'},

    // --- ZONA MÉDIA-BAIXA (2kHz - 3kHz): Nasais e Fricativas Sonoras ---
    // Nasais afetadas por perda em agudos: pistas de F2/F3 de transição
    {'target': 'Mala', 'distractor': 'Bala', 'freq_band': 2800, 'type': 'nasal'},
    {'target': 'Mola', 'distractor': 'Bola', 'freq_band': 2600, 'type': 'nasal'},
    {'target': 'Mudo', 'distractor': 'Budo', 'freq_band': 2900, 'type': 'nasal'},
    {'target': 'Nata', 'distractor': 'Data', 'freq_band': 2500, 'type': 'nasal'},
    {'target': 'Nada', 'distractor': 'Dada', 'freq_band': 2700, 'type': 'nasal'},
    {'target': 'Nobre', 'distractor': 'Dobre', 'freq_band': 2400, 'type': 'nasal'},
    // Fricativas sonoras /z/ — confundidas com /s/ por perda em agudos
    {'target': 'Zona', 'distractor': 'Sona', 'freq_band': 4000, 'type': 'voiced_sibilant'},
    {'target': 'Zaga', 'distractor': 'Saga', 'freq_band': 4200, 'type': 'voiced_sibilant'},
    {'target': 'Zela', 'distractor': 'Sela', 'freq_band': 4100, 'type': 'voiced_sibilant'},

    // --- ITENS DINÂMICOS ---
    {'target': 'Palavra1', 'distractor': 'Falsa1', 'freq_band': 5515, 'type': 'random_rehab'},
    {'target': 'Palavra2', 'distractor': 'Falsa2', 'freq_band': 8008, 'type': 'random_rehab'},
    {'target': 'Palavra3', 'distractor': 'Falsa3', 'freq_band': 5902, 'type': 'random_rehab'},
    {'target': 'Palavra4', 'distractor': 'Falsa4', 'freq_band': 8016, 'type': 'random_rehab'},
    {'target': 'Palavra5', 'distractor': 'Falsa5', 'freq_band': 5046, 'type': 'random_rehab'},
    {'target': 'Palavra6', 'distractor': 'Falsa6', 'freq_band': 7939, 'type': 'random_rehab'},
    {'target': 'Palavra7', 'distractor': 'Falsa7', 'freq_band': 7056, 'type': 'random_rehab'},
    {'target': 'Palavra8', 'distractor': 'Falsa8', 'freq_band': 3683, 'type': 'random_rehab'},
    {'target': 'Palavra9', 'distractor': 'Falsa9', 'freq_band': 3328, 'type': 'random_rehab'},
    {'target': 'Palavra10', 'distractor': 'Falsa10', 'freq_band': 3290, 'type': 'random_rehab'},
    {'target': 'Palavra11', 'distractor': 'Falsa11', 'freq_band': 3832, 'type': 'random_rehab'},
    {'target': 'Palavra12', 'distractor': 'Falsa12', 'freq_band': 4965, 'type': 'random_rehab'},
    {'target': 'Palavra13', 'distractor': 'Falsa13', 'freq_band': 8185, 'type': 'random_rehab'},
    {'target': 'Palavra14', 'distractor': 'Falsa14', 'freq_band': 6695, 'type': 'random_rehab'},
    {'target': 'Palavra15', 'distractor': 'Falsa15', 'freq_band': 7693, 'type': 'random_rehab'},
    {'target': 'Palavra16', 'distractor': 'Falsa16', 'freq_band': 5298, 'type': 'random_rehab'},
    {'target': 'Palavra17', 'distractor': 'Falsa17', 'freq_band': 4468, 'type': 'random_rehab'},
    {'target': 'Palavra18', 'distractor': 'Falsa18', 'freq_band': 4168, 'type': 'random_rehab'},
    {'target': 'Palavra19', 'distractor': 'Falsa19', 'freq_band': 7790, 'type': 'random_rehab'},
    {'target': 'Palavra20', 'distractor': 'Falsa20', 'freq_band': 6800, 'type': 'random_rehab'},
    {'target': 'Palavra21', 'distractor': 'Falsa21', 'freq_band': 5750, 'type': 'random_rehab'},
    {'target': 'Palavra22', 'distractor': 'Falsa22', 'freq_band': 8456, 'type': 'random_rehab'},
    {'target': 'Palavra23', 'distractor': 'Falsa23', 'freq_band': 4249, 'type': 'random_rehab'},
    {'target': 'Palavra24', 'distractor': 'Falsa24', 'freq_band': 4798, 'type': 'random_rehab'},
    {'target': 'Palavra25', 'distractor': 'Falsa25', 'freq_band': 8200, 'type': 'random_rehab'},
    {'target': 'Palavra26', 'distractor': 'Falsa26', 'freq_band': 6463, 'type': 'random_rehab'},
    {'target': 'Palavra27', 'distractor': 'Falsa27', 'freq_band': 8399, 'type': 'random_rehab'},
    {'target': 'Palavra28', 'distractor': 'Falsa28', 'freq_band': 8344, 'type': 'random_rehab'},
    {'target': 'Palavra29', 'distractor': 'Falsa29', 'freq_band': 7667, 'type': 'random_rehab'},
    {'target': 'Palavra30', 'distractor': 'Falsa30', 'freq_band': 4796, 'type': 'random_rehab'},
    {'target': 'Palavra31', 'distractor': 'Falsa31', 'freq_band': 7945, 'type': 'random_rehab'},
    {'target': 'Palavra32', 'distractor': 'Falsa32', 'freq_band': 5555, 'type': 'random_rehab'},
    {'target': 'Palavra33', 'distractor': 'Falsa33', 'freq_band': 6332, 'type': 'random_rehab'},
    {'target': 'Palavra34', 'distractor': 'Falsa34', 'freq_band': 6972, 'type': 'random_rehab'},
    {'target': 'Palavra35', 'distractor': 'Falsa35', 'freq_band': 6945, 'type': 'random_rehab'},
    {'target': 'Palavra36', 'distractor': 'Falsa36', 'freq_band': 6418, 'type': 'random_rehab'},
    {'target': 'Palavra37', 'distractor': 'Falsa37', 'freq_band': 4887, 'type': 'random_rehab'},
    {'target': 'Palavra38', 'distractor': 'Falsa38', 'freq_band': 8378, 'type': 'random_rehab'},
    {'target': 'Palavra39', 'distractor': 'Falsa39', 'freq_band': 6037, 'type': 'random_rehab'},
    {'target': 'Palavra40', 'distractor': 'Falsa40', 'freq_band': 7802, 'type': 'random_rehab'},
    {'target': 'Palavra41', 'distractor': 'Falsa41', 'freq_band': 5097, 'type': 'random_rehab'},
    {'target': 'Palavra42', 'distractor': 'Falsa42', 'freq_band': 5127, 'type': 'random_rehab'},
    {'target': 'Palavra43', 'distractor': 'Falsa43', 'freq_band': 5134, 'type': 'random_rehab'},
    {'target': 'Palavra44', 'distractor': 'Falsa44', 'freq_band': 4787, 'type': 'random_rehab'},
    {'target': 'Palavra45', 'distractor': 'Falsa45', 'freq_band': 3840, 'type': 'random_rehab'},
    {'target': 'Palavra46', 'distractor': 'Falsa46', 'freq_band': 3712, 'type': 'random_rehab'},
    {'target': 'Palavra47', 'distractor': 'Falsa47', 'freq_band': 6545, 'type': 'random_rehab'},
    {'target': 'Palavra48', 'distractor': 'Falsa48', 'freq_band': 3734, 'type': 'random_rehab'},
    {'target': 'Palavra49', 'distractor': 'Falsa49', 'freq_band': 7794, 'type': 'random_rehab'},
    {'target': 'Palavra50', 'distractor': 'Falsa50', 'freq_band': 4566, 'type': 'random_rehab'},
    {'target': 'Palavra51', 'distractor': 'Falsa51', 'freq_band': 5071, 'type': 'random_rehab'},
    {'target': 'Palavra52', 'distractor': 'Falsa52', 'freq_band': 5782, 'type': 'random_rehab'},
    {'target': 'Palavra53', 'distractor': 'Falsa53', 'freq_band': 5019, 'type': 'random_rehab'},
    {'target': 'Palavra54', 'distractor': 'Falsa54', 'freq_band': 6676, 'type': 'random_rehab'},
    {'target': 'Palavra55', 'distractor': 'Falsa55', 'freq_band': 8454, 'type': 'random_rehab'},
    {'target': 'Palavra56', 'distractor': 'Falsa56', 'freq_band': 5745, 'type': 'random_rehab'},
    {'target': 'Palavra57', 'distractor': 'Falsa57', 'freq_band': 6386, 'type': 'random_rehab'},
    {'target': 'Palavra58', 'distractor': 'Falsa58', 'freq_band': 5296, 'type': 'random_rehab'},
    {'target': 'Palavra59', 'distractor': 'Falsa59', 'freq_band': 3339, 'type': 'random_rehab'},
    {'target': 'Palavra60', 'distractor': 'Falsa60', 'freq_band': 7025, 'type': 'random_rehab'},
    {'target': 'Palavra61', 'distractor': 'Falsa61', 'freq_band': 7942, 'type': 'random_rehab'},
    {'target': 'Palavra62', 'distractor': 'Falsa62', 'freq_band': 5965, 'type': 'random_rehab'},
    {'target': 'Palavra63', 'distractor': 'Falsa63', 'freq_band': 8095, 'type': 'random_rehab'},
    {'target': 'Palavra64', 'distractor': 'Falsa64', 'freq_band': 7072, 'type': 'random_rehab'},
    {'target': 'Palavra65', 'distractor': 'Falsa65', 'freq_band': 7844, 'type': 'random_rehab'},
    {'target': 'Palavra66', 'distractor': 'Falsa66', 'freq_band': 8182, 'type': 'random_rehab'},
    {'target': 'Palavra67', 'distractor': 'Falsa67', 'freq_band': 8262, 'type': 'random_rehab'},
    {'target': 'Palavra68', 'distractor': 'Falsa68', 'freq_band': 4725, 'type': 'random_rehab'},
    {'target': 'Palavra69', 'distractor': 'Falsa69', 'freq_band': 7513, 'type': 'random_rehab'},
    {'target': 'Palavra70', 'distractor': 'Falsa70', 'freq_band': 7741, 'type': 'random_rehab'},
  ]
};
